"""New Migration

Revision ID: 68de9b8a72b1
Revises: 706efde8efc6
Create Date: 2024-09-22 18:59:51.033435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68de9b8a72b1'
down_revision = '706efde8efc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
