"""New migration after resetting

Revision ID: 706efde8efc6
Revises: f1c8e5021f8b
Create Date: 2024-09-22 18:37:03.169973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706efde8efc6'
down_revision = 'f1c8e5021f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_mod')
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('_alembic_tmp_mod',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('brand', sa.VARCHAR(), nullable=False),
    sa.Column('model', sa.VARCHAR(), nullable=False),
    sa.Column('yom', sa.INTEGER(), nullable=False),
    sa.Column('budget', sa.INTEGER(), nullable=False),
    sa.Column('genre', sa.VARCHAR(), nullable=False),
    sa.Column('part', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
