"""New Migration

Revision ID: 93b217b85661
Revises: 68de9b8a72b1
Create Date: 2024-09-22 20:17:29.504404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b217b85661'
down_revision = '68de9b8a72b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('budget')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), server_default=sa.text("'Unknown'"), nullable=False))

    # ### end Alembic commands ###
